import { USER_COLLECTION, USER_VERIFICATION_COLLECTION, CHALLENGE_COLLECTION, CHALLENGE_COMPLETION_COLLECTION, SCENE_COLLECTION } from './model/constants';

export default new Set([ USER_COLLECTION, SCENE_COLLECTION, CHALLENGE_COLLECTION, CHALLENGE_COMPLETION_COLLECTION, USER_VERIFICATION_COLLECTION ]);